Repository marlokessler/strapi-plugin-image-optimizer, pull requests merged in 2023-06, with the labels that each got.

#10 Optimize images with extension in ignore case maner
  server/services/image-optimizer-service.ts
Labels: bug

#14 docs: update project documentation
  README.md
Labels: documentation

#16 fix: typing and add additional docs
  README.md
  server/models/config.ts
Labels: documentation, enhancement

#18 Allow transforming for original size, support avif/heif quality
  README.md
  server/services/image-optimizer-service.ts
  strapi-server.js
  tsconfig.json
Labels: enhancement
